name: 24h_Stream
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install FFmpeg
      run: sudo apt-get install -y ffmpeg
    - name: Start Streaming
      timeout-minutes: 355
      run: |
        ffmpeg -re -stream_loop -1 -i video.mp4 \
        -vcodec libx264 -preset veryfast -b:v 1000k -maxrate 1000k -bufsize 2000k \
        -s 854x480 -pix_fmt yuv420p -g 60 -acodec aac -b:a 96k -ar 44100 \
        -f flv "rtmp://a.rtmp.youtube.com/live2/${{ secrets.STREAM_KEY }}"
